"""Machine-readable LOLBin/GTFOBin/LOOBin threat intelligence.

Data sources:
- LOLBAS: https://github.com/LOLBAS-Project/LOLBAS (Windows)
- GTFOBins: https://github.com/GTFOBins/GTFOBins.github.io (Linux/macOS)
- LOOBins: https://github.com/infosecB/LOOBins (macOS)
"""

from __future__ import annotations

# LOLBAS — Windows Living Off the Land Binaries
# 127 binaries
LOLBAS_BINARIES: dict[str, dict] = {
    "addinutil": {
        "desc": ".NET Tool used for updating cache files for Microsoft Office Add-Ins.",
        "functions": ["Execute"],
    },
    "appinstaller": {
        "desc": "Tool used for installation of AppX/MSIX applications on Windows 10",
        "functions": ["Download"],
    },
    "aspnet_compiler": {"desc": "ASP.NET Compilation Tool", "functions": ["AWL Bypass"]},
    "at": {"desc": "Schedule periodic tasks", "functions": ["Execute"]},
    "atbroker": {"desc": "Helper binary for Assistive Technology (AT)", "functions": ["Execute"]},
    "bash": {"desc": "File used by Windows subsystem for Linux", "functions": ["AWL Bypass", "Execute"]},
    "bitsadmin": {
        "desc": "Used for managing background intelligent transfer",
        "functions": ["ADS", "Copy", "Download", "Execute"],
    },
    "certoc": {"desc": "Used for installing certificates", "functions": ["Download", "Execute"]},
    "certreq": {"desc": "Used for requesting and managing certificates", "functions": ["Download", "Upload"]},
    "certutil": {
        "desc": "Windows binary used for handling certificates",
        "functions": ["ADS", "Decode", "Download", "Encode"],
    },
    "change": {"desc": "Remote Desktop Services MultiUser Change Utility", "functions": ["Execute"]},
    "cipher": {"desc": "File Encryption Utility", "functions": ["Tamper"]},
    "cmd": {"desc": "The command-line interpreter in Windows", "functions": ["ADS", "Download", "Upload"]},
    "cmdkey": {
        "desc": "creates, lists, and deletes stored user names and passwords or credentials.",
        "functions": ["Credentials"],
    },
    "cmdl32": {"desc": "Microsoft Connection Manager Auto-Download", "functions": ["Download"]},
    "cmstp": {
        "desc": "Installs or removes a Connection Manager service profile.",
        "functions": ["AWL Bypass", "Execute"],
    },
    "colorcpl": {"desc": "Binary that handles color management", "functions": ["Copy"]},
    "computerdefaults": {
        "desc": "ComputerDefaults.exe is a Windows system utility for managing default applications for tasks like web browsing, emailing",
        "functions": ["UAC Bypass"],
    },
    "configsecuritypolicy": {
        "desc": "Binary part of Windows Defender. Used to manage settings in Windows Defender. You can configure different pilot collecti",
        "functions": ["Download", "Upload"],
    },
    "conhost": {"desc": "Console Window host", "functions": ["Execute"]},
    "control": {"desc": "Binary used to launch controlpanel items in Windows", "functions": ["ADS", "Execute"]},
    "csc": {"desc": "Binary file used by .NET Framework to compile C# code", "functions": ["Compile"]},
    "cscript": {"desc": "Binary used to execute scripts in Windows", "functions": ["ADS"]},
    "customshellhost": {
        "desc": "A host process that is used by custom shells when using Windows in Kiosk mode.",
        "functions": ["Execute"],
    },
    "datasvcutil": {
        "desc": "DataSvcUtil.exe is a command-line tool provided by WCF Data Services that consumes an Open Data Protocol (OData) feed an",
        "functions": ["Upload"],
    },
    "desktopimgdownldr": {
        "desc": "Windows binary used to configure lockscreen/desktop image",
        "functions": ["Download"],
    },
    "devicecredentialdeployment": {"desc": "Device Credential Deployment", "functions": ["Conceal"]},
    "dfsvc": {"desc": "ClickOnce engine in Windows used by .NET", "functions": ["AWL Bypass"]},
    "diantz": {
        "desc": "Binary that package existing files into a cabinet (.cab) file",
        "functions": ["ADS", "Download", "Execute"],
    },
    "diskshadow": {
        "desc": "Diskshadow.exe is a tool that exposes the functionality offered by the volume shadow copy Service (VSS).",
        "functions": ["Dump", "Execute"],
    },
    "dnscmd": {"desc": "A command-line interface for managing DNS servers", "functions": ["Execute"]},
    "esentutl": {
        "desc": "Binary for working with Microsoft Joint Engine Technology (JET) database",
        "functions": ["ADS", "Copy", "Download"],
    },
    "eudcedit": {"desc": "Private Character Editor Windows Utility", "functions": ["UAC Bypass"]},
    "eventvwr": {"desc": "Displays Windows Event Logs in a GUI window.", "functions": ["UAC Bypass"]},
    "expand": {"desc": "Binary that expands one or more compressed files", "functions": ["ADS", "Copy", "Download"]},
    "explorer": {
        "desc": "Binary used for managing files and system components within Windows",
        "functions": ["Execute"],
    },
    "extexport": {"desc": "Load a DLL located in the c:\test folder with a specific name.", "functions": ["Execute"]},
    "extrac32": {
        "desc": "Extract to ADS, copy or overwrite a file with Extrac32.exe",
        "functions": ["ADS", "Copy", "Download"],
    },
    "findstr": {
        "desc": "Write to ADS, discover, or download files with Findstr.exe",
        "functions": ["ADS", "Credentials", "Download"],
    },
    "finger": {
        "desc": "Displays information about a user or users on a specified remote computer that is running the Finger service or daemon",
        "functions": ["Download"],
    },
    "fltmc": {"desc": "Filter Manager Control Program used by Windows", "functions": ["Tamper"]},
    "forfiles": {
        "desc": "Selects and executes a command on a file or set of files. This command is useful for batch processing.",
        "functions": ["ADS", "Execute"],
    },
    "fsutil": {"desc": "File System Utility", "functions": ["Execute", "Tamper"]},
    "ftp": {"desc": "A binary designed for connecting to FTP servers", "functions": ["Download", "Execute"]},
    "gpscript": {"desc": "Used by group policy to process scripts", "functions": ["Execute"]},
    "hh": {"desc": "Binary used for processing chm files in Windows", "functions": ["Download", "Execute"]},
    "ie4uinit": {"desc": "Executes commands from a specially prepared ie4uinit.inf file.", "functions": ["Execute"]},
    "iediagcmd": {"desc": "Diagnostics Utility for Internet Explorer", "functions": ["Execute"]},
    "ieexec": {
        "desc": "The IEExec.exe application is an undocumented Microsoft .NET Framework application that is included with the .NET Framew",
        "functions": ["Download", "Execute"],
    },
    "ilasm": {"desc": "used for compile c# code into dll or exe.", "functions": ["Compile"]},
    "imewdbld": {"desc": "Microsoft IME Open Extended Dictionary Module", "functions": ["Download"]},
    "infdefaultinstall": {
        "desc": "Binary used to perform installation based on content inside inf files",
        "functions": ["Execute"],
    },
    "installutil": {
        "desc": "The Installer tool is a command-line utility that allows you to install and uninstall server resources by executing the ",
        "functions": ["AWL Bypass", "Download", "Execute"],
    },
    "iscsicpl": {"desc": "Microsoft iSCSI Initiator Control Panel tool", "functions": ["UAC Bypass"]},
    "jsc": {
        "desc": "Binary file used by .NET to compile JavaScript code to .exe or .dll format",
        "functions": ["Compile"],
    },
    "ldifde": {"desc": "Creates, modifies, and deletes LDAP directory objects.", "functions": ["Download"]},
    "makecab": {
        "desc": "Binary to package existing files into a cabinet (.cab) file",
        "functions": ["ADS", "Download", "Execute"],
    },
    "mavinject": {"desc": "Used by App-v in Windows", "functions": ["ADS", "Execute"]},
    "microsoft.workflow.compiler": {
        "desc": "A utility included with .NET that is capable of compiling and executing C# or VB.net code.",
        "functions": ["AWL Bypass", "Execute"],
    },
    "mmc": {
        "desc": "Load snap-ins to locally and remotely manage Windows systems",
        "functions": ["Download", "Execute", "UAC Bypass"],
    },
    "mpcmdrun": {
        "desc": "Binary part of Windows Defender. Used to manage settings in Windows Defender",
        "functions": ["ADS", "Download"],
    },
    "msbuild": {"desc": "Used to compile and execute code", "functions": ["AWL Bypass", "Execute"]},
    "msconfig": {
        "desc": "MSConfig is a troubleshooting tool which is used to temporarily disable or re-enable software, device drivers or Windows",
        "functions": ["Execute"],
    },
    "msdt": {"desc": "Microsoft diagnostics tool", "functions": ["AWL Bypass", "Execute"]},
    "msedge": {"desc": "Microsoft Edge browser", "functions": ["Download", "Execute"]},
    "msedge_proxy": {"desc": "Microsoft Edge Browser", "functions": ["Download", "Execute"]},
    "msedgewebview2": {
        "desc": "msedgewebview2.exe is the executable file for Microsoft Edge WebView2, which is a web browser control used by applicatio",
        "functions": ["Execute"],
    },
    "mshta": {
        "desc": "Used by Windows to execute html applications. (.hta)",
        "functions": ["ADS", "Download", "Execute"],
    },
    "msiexec": {"desc": "Used by Windows to execute msi files", "functions": ["Execute"]},
    "netsh": {
        "desc": "Netsh is a Windows tool used to manipulate network interface settings.",
        "functions": ["Execute"],
    },
    "ngen": {"desc": "Microsoft Native Image Generator.", "functions": ["Download"]},
    "odbcconf": {"desc": "Used in Windows for managing ODBC connections", "functions": ["Execute"]},
    "offlinescannershell": {"desc": "Windows Defender Offline Shell", "functions": ["Execute"]},
    "onedrivestandaloneupdater": {"desc": "OneDrive Standalone Updater", "functions": ["Download"]},
    "pcalua": {"desc": "Program Compatibility Assistant", "functions": ["Execute"]},
    "pcwrun": {"desc": "Program Compatibility Wizard", "functions": ["Execute"]},
    "pktmon": {
        "desc": "Capture Network Packets on the windows 10 with October 2018 Update or later.",
        "functions": ["Reconnaissance"],
    },
    "pnputil": {"desc": "Used for installing drivers", "functions": ["Execute"]},
    "presentationhost": {
        "desc": "File is used for executing Browser applications",
        "functions": ["Download", "Execute"],
    },
    "print": {"desc": "Used by Windows to send files to the printer", "functions": ["ADS", "Copy"]},
    "printbrm": {"desc": "Printer Migration Command-Line Tool", "functions": ["ADS", "Download"]},
    "provlaunch": {"desc": "Launcher process", "functions": ["Execute"]},
    "psr": {
        "desc": "Windows Problem Steps Recorder, used to record screen and clicks.",
        "functions": ["Reconnaissance"],
    },
    "query": {"desc": "Remote Desktop Services MultiUser Query Utility", "functions": ["Execute"]},
    "rasautou": {"desc": "Windows Remote Access Dialer", "functions": ["Execute"]},
    "rdrleakdiag": {"desc": "Microsoft Windows resource leak diagnostic tool", "functions": ["Dump"]},
    "reg": {"desc": "Used to manipulate the registry", "functions": ["ADS", "Credentials"]},
    "regasm": {"desc": "Part of .NET", "functions": ["AWL Bypass", "Execute"]},
    "regedit": {"desc": "Used by Windows to manipulate registry", "functions": ["ADS"]},
    "regini": {"desc": "Used to manipulate the registry", "functions": ["ADS"]},
    "register-cimprovider": {"desc": "Used to register new wmi providers", "functions": ["Execute"]},
    "regsvcs": {
        "desc": "Regsvcs and Regasm are Windows command-line utilities that are used to register .NET Component Object Model (COM) assemb",
        "functions": ["AWL Bypass", "Execute"],
    },
    "regsvr32": {"desc": "Used by Windows to register dlls", "functions": ["AWL Bypass", "Execute"]},
    "replace": {"desc": "Used to replace file with another file", "functions": ["Copy", "Download"]},
    "reset": {"desc": "Remote Desktop Services Reset Utility", "functions": ["Execute"]},
    "rpcping": {"desc": "Used to verify rpc connection", "functions": ["Credentials"]},
    "rundll32": {"desc": "Used by Windows to execute dll files", "functions": ["ADS", "Execute"]},
    "runexehelper": {"desc": "Launcher process", "functions": ["Execute"]},
    "runonce": {"desc": "Executes a Run Once Task that has been configured in the registry", "functions": ["Execute"]},
    "runscripthelper": {"desc": "Execute target PowerShell script", "functions": ["Execute"]},
    "sc": {"desc": "Used by Windows to manage services", "functions": ["ADS"]},
    "schtasks": {"desc": "Schedule periodic tasks", "functions": ["Execute"]},
    "scriptrunner": {
        "desc": "Execute binary through proxy binary to evade defensive counter measures",
        "functions": ["Execute"],
    },
    "setres": {"desc": "Configures display settings", "functions": ["Execute"]},
    "settingsynchost": {"desc": "Host Process for Setting Synchronization", "functions": ["Execute"]},
    "sftp": {
        "desc": "sftp.exe is a Windows command-line utility that uses the Secure File Transfer Protocol (SFTP) to securely transfer files",
        "functions": ["Execute"],
    },
    "ssh": {
        "desc": "Ssh.exe is the OpenSSH compatible client can be used to connect to Windows 10 (build 1809 and later) and Windows Server ",
        "functions": ["Execute"],
    },
    "stordiag": {"desc": "Storage diagnostic tool", "functions": ["Execute"]},
    "syncappvpublishingserver": {"desc": "Used by App-v to get App-v server lists", "functions": ["Execute"]},
    "tar": {"desc": "Used by Windows to extract and create archives.", "functions": ["ADS", "Copy"]},
    "ttdinject": {
        "desc": "Used by Windows 1809 and newer to Debug Time Travel (Underlying call of tttracer.exe)",
        "functions": ["Execute"],
    },
    "tttracer": {"desc": "Used by Windows 1809 and newer to Debug Time Travel", "functions": ["Dump", "Execute"]},
    "unregmp2": {"desc": "Microsoft Windows Media Player Setup Utility", "functions": ["Execute"]},
    "vbc": {"desc": "Binary file used for compile vbs code", "functions": ["Compile"]},
    "verclsid": {
        "desc": "Used to verify a COM object before it is instantiated by Windows Explorer",
        "functions": ["Execute"],
    },
    "wab": {"desc": "Windows address book manager", "functions": ["Execute"]},
    "wbadmin": {"desc": "Windows Backup Administration utility", "functions": ["Dump"]},
    "wbemtest": {"desc": "WMI/WBEM Test Binary", "functions": ["Execute"]},
    "winget": {"desc": "Windows Package Manager tool", "functions": ["AWL Bypass", "Download", "Execute"]},
    "wlrmdr": {"desc": "Windows Logon Reminder executable", "functions": ["Execute"]},
    "wmic": {
        "desc": "The WMI command-line (WMIC) utility provides a command-line interface for WMI",
        "functions": ["ADS", "Copy", "Execute"],
    },
    "workfolders": {"desc": "Work Folders", "functions": ["Execute"]},
    "wscript": {"desc": "Used by Windows to execute scripts", "functions": ["ADS"]},
    "wsreset": {
        "desc": "Used to reset Windows Store settings according to its manifest file",
        "functions": ["UAC Bypass"],
    },
    "wt": {"desc": "Windows Terminal", "functions": ["Execute"]},
    "wuauclt": {"desc": "Windows Update Client", "functions": ["Execute"]},
    "xwizard": {
        "desc": "Execute custom class that has been added to the registry or download a file with Xwizard.exe",
        "functions": ["Download", "Execute"],
    },
}

# GTFOBins — Linux/macOS privilege escalation and escape
# 453 binaries
GTFOBINS_BINARIES: dict[str, list[str]] = {
    "7z": ["file-read"],
    "R": ["shell"],
    "aa-exec": ["shell"],
    "ab": ["download", "upload"],
    "acr": ["command"],
    "agetty": ["shell"],
    "alpine": ["file-read"],
    "ansible-playbook": ["shell"],
    "ansible-test": ["shell"],
    "aoss": ["shell"],
    "apache2": ["file-read"],
    "apache2ctl": ["file-read"],
    "apport-cli": ["inherit"],
    "apt-get": ["inherit", "shell"],
    "aptitude": ["inherit"],
    "ar": ["file-read"],
    "arch-nspawn": ["shell"],
    "aria2c": ["command", "download", "file-read"],
    "arj": ["file-read", "file-write"],
    "arp": ["file-read"],
    "as": ["file-read"],
    "ascii-xfr": ["file-read"],
    "ascii85": ["file-read"],
    "ash": ["file-write", "shell"],
    "aspell": ["file-read"],
    "asterisk": ["shell"],
    "at": ["command", "shell"],
    "atobm": ["file-read"],
    "autoconf": ["shell"],
    "autoheader": ["shell"],
    "autoreconf": ["shell"],
    "aws": ["file-read", "inherit"],
    "base32": ["file-read"],
    "base58": ["file-read"],
    "base64": ["file-read"],
    "basenc": ["file-read"],
    "basez": ["file-read"],
    "bash": ["download", "file-read", "file-write", "library-load", "reverse-shell", "shell", "upload"],
    "bashbug": ["inherit"],
    "batcat": ["inherit"],
    "bc": ["file-read"],
    "bconsole": ["file-read", "shell"],
    "bee": ["inherit"],
    "borg": ["shell"],
    "bpftrace": ["shell"],
    "bridge": ["file-read"],
    "bundle": ["inherit", "shell"],
    "busctl": ["inherit", "shell"],
    "busybox": ["inherit", "reverse-shell", "upload"],
    "byebug": ["inherit"],
    "bzip2": ["file-read"],
    "cabal": ["shell"],
    "cancel": ["upload"],
    "capsh": ["shell"],
    "cargo": ["inherit"],
    "cat": ["file-read"],
    "cdist": ["shell"],
    "certbot": ["shell"],
    "chattr": ["privilege-escalation"],
    "check_by_ssh": ["shell"],
    "check_cups": ["file-read"],
    "check_log": ["file-read", "file-write"],
    "check_memory": ["file-read"],
    "check_raid": ["file-read"],
    "check_ssl_cert": ["shell"],
    "check_statusfile": ["file-read"],
    "chmod": ["privilege-escalation"],
    "choom": ["shell"],
    "chown": ["privilege-escalation"],
    "chroot": ["shell"],
    "chrt": ["shell"],
    "clamscan": ["file-read"],
    "clisp": ["shell"],
    "cmake": ["file-read", "shell"],
    "cmp": ["file-read"],
    "cobc": ["shell"],
    "code": ["download", "reverse-shell", "upload"],
    "column": ["file-read"],
    "comm": ["file-read"],
    "composer": ["shell"],
    "cowsay": ["inherit"],
    "cowthink": ["inherit"],
    "cp": ["file-read", "file-write", "privilege-escalation"],
    "cpan": ["inherit"],
    "cpio": ["file-read", "file-write", "shell"],
    "cpulimit": ["shell"],
    "crash": ["command", "inherit"],
    "crontab": ["command", "inherit"],
    "csh": ["file-write", "shell"],
    "csplit": ["file-read", "file-write"],
    "csvtool": ["file-read", "file-write", "shell"],
    "ctr": ["shell"],
    "cupsfilter": ["file-read"],
    "curl": ["download", "file-read", "file-write", "library-load", "upload"],
    "cut": ["file-read"],
    "dash": ["file-write", "shell"],
    "date": ["file-read"],
    "dc": ["shell"],
    "dd": ["file-read", "file-write"],
    "debugfs": ["shell"],
    "dhclient": ["shell"],
    "dialog": ["file-read"],
    "diff": ["file-read"],
    "dig": ["file-read"],
    "distcc": ["shell"],
    "dmesg": ["file-read", "inherit"],
    "dmidecode": ["file-write"],
    "dmsetup": ["shell"],
    "dnf": ["command"],
    "dnsmasq": ["command"],
    "doas": ["shell"],
    "docker": ["file-read", "file-write", "shell"],
    "dos2unix": ["file-read", "file-write"],
    "dosbox": ["file-read", "file-write"],
    "dotnet": ["file-read", "shell"],
    "dpkg": ["inherit", "shell"],
    "dstat": ["inherit"],
    "dvips": ["shell"],
    "easy_install": ["inherit"],
    "easyrsa": ["shell"],
    "eb": ["inherit"],
    "ed": ["file-read", "file-write", "shell"],
    "efax": ["file-read"],
    "egrep": ["file-read"],
    "elvish": ["file-read", "file-write", "shell"],
    "emacs": ["file-read", "file-write", "shell"],
    "enscript": ["shell"],
    "env": ["shell"],
    "eqn": ["file-read"],
    "espeak": ["file-read"],
    "ex": ["inherit", "shell"],
    "exiftool": ["file-read", "file-write", "inherit"],
    "expand": ["file-read"],
    "expect": ["file-read", "shell"],
    "facter": ["inherit"],
    "fail2ban-client": ["command"],
    "ffmpeg": ["library-load"],
    "fgrep": ["file-read"],
    "file": ["file-read"],
    "find": ["file-read", "file-write", "shell"],
    "finger": ["download", "upload"],
    "firejail": ["shell"],
    "fish": ["shell"],
    "flock": ["shell"],
    "fmt": ["file-read"],
    "fold": ["file-read"],
    "forge": ["shell"],
    "fping": ["file-read"],
    "ftp": ["download", "shell", "upload"],
    "fzf": ["command", "shell"],
    "gawk": ["bind-shell", "file-read", "file-write", "reverse-shell", "shell"],
    "gcc": ["file-read", "file-write", "shell"],
    "gcloud": ["inherit"],
    "gcore": ["file-read"],
    "gdb": ["file-write", "inherit", "shell"],
    "gem": ["inherit", "shell"],
    "genie": ["shell"],
    "genisoimage": ["file-read"],
    "getent": ["privilege-escalation"],
    "ghc": ["shell"],
    "ghci": ["shell"],
    "gimp": ["inherit"],
    "ginsh": ["shell"],
    "git": ["file-read", "file-write", "inherit", "shell"],
    "gnuplot": ["shell"],
    "go": ["bind-shell", "file-read", "file-write", "reverse-shell", "shell"],
    "grc": ["shell"],
    "grep": ["file-read"],
    "gtester": ["file-write", "shell"],
    "guile": ["shell"],
    "gzip": ["file-read"],
    "hashcat": ["file-write"],
    "head": ["file-read"],
    "hexdump": ["file-read"],
    "hg": ["shell"],
    "highlight": ["file-read"],
    "hping3": ["shell", "upload"],
    "iconv": ["file-read", "file-write"],
    "iftop": ["shell"],
    "install": ["privilege-escalation"],
    "ionice": ["shell"],
    "ip": ["file-read", "shell"],
    "iptables-save": ["file-write"],
    "irb": ["inherit"],
    "ispell": ["shell"],
    "java": ["shell"],
    "jjs": ["download", "file-read", "file-write", "reverse-shell", "shell"],
    "joe": ["shell"],
    "join": ["file-read"],
    "journalctl": ["inherit"],
    "jq": ["file-read"],
    "jrunscript": ["download", "file-read", "file-write", "reverse-shell", "shell"],
    "jshell": ["file-read", "file-write", "shell"],
    "jtag": ["shell"],
    "julia": ["download", "file-read", "file-write", "reverse-shell", "shell"],
    "knife": ["inherit"],
    "ksshell": ["file-read"],
    "ksu": ["shell"],
    "kubectl": ["shell", "upload"],
    "last": ["file-read"],
    "latex": ["file-read", "file-write", "shell"],
    "latexmk": ["file-read", "inherit", "shell"],
    "ld.so": ["shell"],
    "ldconfig": ["library-load"],
    "less": ["command", "file-read", "file-write", "inherit", "shell"],
    "lftp": ["shell"],
    "links": ["file-read"],
    "ln": ["privilege-escalation"],
    "loginctl": ["shell"],
    "logrotate": ["file-read", "file-write", "shell"],
    "logsave": ["shell"],
    "look": ["file-read"],
    "lp": ["upload"],
    "ltrace": ["file-read", "file-write", "shell"],
    "lua": ["bind-shell", "download", "file-read", "file-write", "reverse-shell", "shell", "upload"],
    "lualatex": ["inherit"],
    "luatex": ["inherit"],
    "lwp-download": ["download", "file-read", "file-write"],
    "lwp-request": ["file-read"],
    "lxd": ["shell"],
    "m4": ["command", "file-read", "shell"],
    "mail": ["shell"],
    "make": ["file-read", "file-write", "shell"],
    "man": ["file-read", "inherit", "shell"],
    "mawk": ["file-read", "file-write", "shell"],
    "minicom": ["shell"],
    "more": ["file-read", "shell"],
    "mosh-server": ["shell"],
    "mosquitto": ["file-read"],
    "mount": ["privilege-escalation"],
    "msfconsole": ["inherit"],
    "msgattrib": ["file-read"],
    "msgcat": ["file-read"],
    "msgconv": ["file-read"],
    "msgfilter": ["file-read", "shell"],
    "msgmerge": ["file-read"],
    "msguniq": ["file-read"],
    "mtr": ["file-read"],
    "multitime": ["shell"],
    "mutt": ["file-read"],
    "mv": ["file-write", "privilege-escalation"],
    "mypy": ["file-read", "file-write"],
    "mysql": ["library-load", "shell"],
    "nano": ["file-read", "file-write", "shell"],
    "nasm": ["file-read"],
    "nc": ["bind-shell", "download", "reverse-shell", "upload"],
    "ncdu": ["shell"],
    "ncftp": ["shell"],
    "neofetch": ["file-read", "shell"],
    "nft": ["file-read"],
    "nginx": ["download", "library-load", "upload"],
    "nice": ["shell"],
    "nl": ["file-read"],
    "nm": ["file-read"],
    "nmap": ["file-read", "file-write", "inherit", "shell"],
    "node": ["bind-shell", "download", "file-read", "file-write", "reverse-shell", "shell", "upload"],
    "nohup": ["command", "shell"],
    "npm": ["shell"],
    "nroff": ["file-read", "shell"],
    "nsenter": ["shell"],
    "ntpdate": ["file-read"],
    "octave": ["file-read", "file-write", "shell"],
    "od": ["file-read"],
    "openssl": ["download", "file-read", "file-write", "library-load", "reverse-shell", "upload"],
    "openvpn": ["file-read", "shell"],
    "openvt": ["command"],
    "opkg": ["shell"],
    "pandoc": ["file-read", "file-write", "inherit"],
    "passwd": ["privilege-escalation"],
    "paste": ["file-read"],
    "pax": ["file-read"],
    "pdb": ["inherit"],
    "pdflatex": ["file-read", "file-write", "shell"],
    "pdftex": ["shell"],
    "perf": ["shell"],
    "perl": ["download", "file-read", "reverse-shell", "shell", "upload"],
    "perlbug": ["shell"],
    "pexec": ["shell"],
    "pg": ["file-read", "shell"],
    "php": ["command", "download", "file-read", "file-write", "reverse-shell", "shell", "upload"],
    "pic": ["file-read", "shell"],
    "pidstat": ["shell"],
    "pip": ["inherit", "shell"],
    "pipx": ["inherit"],
    "pkexec": ["shell"],
    "pkg": ["command"],
    "plymouth": ["shell"],
    "podman": ["shell"],
    "poetry": ["inherit"],
    "posh": ["shell"],
    "pr": ["file-read"],
    "procmail": ["command"],
    "pry": ["inherit"],
    "psftp": ["shell"],
    "psql": ["inherit", "shell"],
    "ptx": ["file-read"],
    "puppet": ["file-read", "file-write", "shell"],
    "pwsh": ["file-write", "shell"],
    "pygmentize": ["file-read"],
    "pyright": ["file-read"],
    "python": ["download", "file-read", "file-write", "library-load", "reverse-shell", "shell", "upload"],
    "qpdf": ["file-read"],
    "rake": ["file-read", "inherit"],
    "ranger": ["shell"],
    "rc": ["shell"],
    "readelf": ["file-read"],
    "redcarpet": ["file-read"],
    "redis": ["file-write"],
    "restic": ["command", "shell", "upload"],
    "rev": ["file-read"],
    "rlogin": ["upload"],
    "rlwrap": ["file-write", "shell"],
    "rpm": ["command", "inherit", "shell"],
    "rpmdb": ["inherit", "shell"],
    "rpmquery": ["inherit", "shell"],
    "rpmverify": ["inherit", "shell"],
    "rsync": ["shell"],
    "rsyslogd": ["command"],
    "rtorrent": ["shell"],
    "ruby": ["download", "file-read", "file-write", "library-load", "reverse-shell", "shell", "upload"],
    "run-mailcap": ["inherit"],
    "run-parts": ["shell"],
    "runscript": ["shell"],
    "rustc": ["file-read", "file-write", "inherit"],
    "rustdoc": ["file-read", "file-write"],
    "rustfmt": ["file-read"],
    "rustup": ["command", "shell"],
    "sash": ["shell"],
    "scanmem": ["shell"],
    "scp": ["download", "shell", "upload"],
    "screen": ["file-write", "shell"],
    "script": ["file-write", "shell"],
    "scrot": ["shell"],
    "sed": ["file-read", "file-write", "shell"],
    "service": ["shell"],
    "setarch": ["shell"],
    "setcap": ["privilege-escalation"],
    "setfacl": ["privilege-escalation"],
    "setlock": ["shell"],
    "sftp": ["download", "shell", "upload"],
    "sg": ["shell"],
    "shred": ["file-write"],
    "shuf": ["file-read", "file-write"],
    "slsh": ["shell"],
    "smbclient": ["download", "shell", "upload"],
    "snap": ["command"],
    "socat": ["bind-shell", "download", "file-read", "file-write", "reverse-shell", "shell", "upload"],
    "socket": ["bind-shell", "reverse-shell"],
    "soelim": ["file-read"],
    "softlimit": ["shell"],
    "sort": ["file-read", "file-write"],
    "split": ["file-read", "file-write", "shell"],
    "sqlite3": ["file-read", "file-write", "shell"],
    "sqlmap": ["inherit"],
    "ss": ["file-read"],
    "ssh": ["download", "file-read", "shell", "upload"],
    "ssh-agent": ["shell"],
    "ssh-copy-id": ["file-read", "file-write"],
    "ssh-keygen": ["library-load"],
    "ssh-keyscan": ["file-read"],
    "sshfs": ["command", "download", "shell", "upload"],
    "sshpass": ["shell"],
    "sshuttle": ["shell"],
    "start-stop-daemon": ["shell"],
    "stdbuf": ["shell"],
    "strace": ["file-write", "shell"],
    "strings": ["file-read"],
    "su": ["shell"],
    "sudo": ["shell"],
    "sysctl": ["command", "file-read"],
    "systemctl": ["inherit", "shell"],
    "systemd-resolve": ["inherit"],
    "systemd-run": ["command", "shell"],
    "tac": ["file-read"],
    "tail": ["file-read"],
    "tailscale": ["upload"],
    "tar": ["download", "file-read", "file-write", "shell", "upload"],
    "task": ["shell"],
    "taskset": ["shell"],
    "tasksh": ["shell"],
    "tbl": ["file-read"],
    "tclsh": ["library-load", "reverse-shell", "shell"],
    "tcpdump": ["command", "file-write"],
    "tcsh": ["file-write", "shell"],
    "tdbtool": ["shell"],
    "tee": ["file-write"],
    "telnet": ["reverse-shell", "shell"],
    "terraform": ["file-read"],
    "tex": ["shell"],
    "tftp": ["download", "upload"],
    "tic": ["file-read"],
    "time": ["shell"],
    "timedatectl": ["inherit"],
    "timeout": ["shell"],
    "tmate": ["shell"],
    "tmux": ["file-read", "shell"],
    "top": ["shell"],
    "torify": ["shell"],
    "torsocks": ["shell"],
    "troff": ["file-read"],
    "tsc": ["file-read", "file-write"],
    "tshark": ["inherit"],
    "ul": ["file-read"],
    "unexpand": ["file-read"],
    "uniq": ["file-read"],
    "unshare": ["shell"],
    "unsquashfs": ["privilege-escalation"],
    "unzip": ["privilege-escalation"],
    "update-alternatives": ["file-write"],
    "urlget": ["file-read"],
    "uuencode": ["file-read"],
    "uv": ["shell"],
    "vagrant": ["inherit"],
    "valgrind": ["shell"],
    "varnishncsa": ["file-write"],
    "vi": ["file-read", "file-write", "shell"],
    "vigr": ["inherit"],
    "vim": ["file-read", "inherit"],
    "vipw": ["inherit"],
    "virsh": ["command", "file-write"],
    "volatility": ["inherit"],
    "w3m": ["file-read"],
    "wall": ["file-read"],
    "watch": ["shell"],
    "wc": ["file-read"],
    "wg-quick": ["shell"],
    "wget": ["download", "file-read", "file-write", "shell", "upload"],
    "whiptail": ["file-read"],
    "whois": ["download", "upload"],
    "wireshark": ["file-write", "inherit"],
    "wish": ["inherit"],
    "xargs": ["file-read", "shell"],
    "xdg-user-dir": ["shell"],
    "xdotool": ["shell"],
    "xmodmap": ["file-read"],
    "xmore": ["file-read"],
    "xpad": ["file-read"],
    "xxd": ["file-read", "file-write"],
    "xz": ["file-read"],
    "yarn": ["shell"],
    "yash": ["shell"],
    "yelp": ["file-read"],
    "yt-dlp": ["shell"],
    "yum": ["command", "download", "inherit"],
    "zathura": ["shell"],
    "zcat": ["file-read"],
    "zgrep": ["file-read"],
    "zic": ["command"],
    "zip": ["file-read", "shell"],
    "zless": ["inherit"],
    "zsh": ["file-read", "file-write", "inherit", "shell"],
    "zsoelim": ["file-read"],
    "zypper": ["shell"],
}

# LOOBins — macOS Living Off the Orchard
# 58 binaries
LOOBINS_BINARIES: dict[str, dict] = {
    "GetFileInfo": {"desc": "Get attributes of files and directories.", "functions": ["Discovery"]},
    "SetFile": {"desc": "Set attributes of files and directories.", "functions": ["Defense Evasion", "Persistence"]},
    "caffeinate": {
        "desc": "Prevent the system from sleeping on behalf of a utility.",
        "functions": ["Defense Evasion", "Execution"],
    },
    "chflags": {"desc": "Changes file or directory flags", "functions": ["Defense Evasion"]},
    "codesign": {"desc": "Create, manipulate and verify code signatures.", "functions": ["Defense Evasion"]},
    "csrutil": {
        "desc": "Configure or view system security policies.",
        "functions": ["Defense Evasion", "Discovery", "Reconnaissance"],
    },
    "defaults": {
        "desc": "Read, write, and delete user preference values.",
        "functions": ["Defense Evasion", "Discovery", "Persistence"],
    },
    "disown": {
        "desc": "Prevents a process from being terminated when a shell session or terminal is closed.",
        "functions": ["Persistence"],
    },
    "ditto": {
        "desc": "Copy files and directories while preserving file attributes and permissions.",
        "functions": ["Collection", "Defense Evasion", "Exfiltration", "Lateral Movement", "Persistence"],
    },
    "dns-sd": {
        "desc": "Discover local network services using the DNS-Based Service Discovery (SD) protocol.",
        "functions": ["Discovery"],
    },
    "dscacheutil": {
        "desc": "Gather information, statistics and initiate queries to the Directory Service cache.",
        "functions": ["Discovery"],
    },
    "dscl": {"desc": "Interact with Directory Services.", "functions": ["Discovery", "Persistence"]},
    "dsconfigad": {
        "desc": "Retrieves/changes configuration for Directory Services Active Directory Plugin.",
        "functions": ["Discovery"],
    },
    "dsexport": {
        "desc": "Export data from an Open Directory directory services server.",
        "functions": ["Discovery", "Reconnaissance"],
    },
    "hdiutil": {
        "desc": "Manipulate disk images using the DiskImages framework.",
        "functions": ["Collection", "Execution"],
    },
    "ioreg": {
        "desc": "Displays a hierarchical view of the I/O Kit registry.",
        "functions": ["Collection", "Discovery"],
    },
    "kextstat": {"desc": "Display the status of loaded kernel extensions (kexts)", "functions": ["Discovery"]},
    "last": {"desc": "Show last user logins and TTYs.", "functions": ["Discovery"]},
    "launchctl": {"desc": "Interact with LaunchAgents and LaunchDaemons.", "functions": ["Execution", "Persistence"]},
    "log": {
        "desc": "Access system log messages from Apple Unified Logging (AUL).",
        "functions": ["Credential Access", "Defense Evasion"],
    },
    "lsregister": {"desc": "Interact with the macOS Launch Services database.", "functions": ["Discovery", "Impact"]},
    "mdfind": {
        "desc": "Locate files using the Spotlight database.",
        "functions": ["Defense Evasion", "Discovery", "Reconnaissance"],
    },
    "mdls": {"desc": "List metadata attributes for the specified file.", "functions": ["Defense Evasion", "Discovery"]},
    "mktemp": {
        "desc": "Create a temporary file or directory and return the file/directory name to stdout",
        "functions": ["Defense Evasion"],
    },
    "networksetup": {
        "desc": "Configure network settings in System Preferences.",
        "functions": ["Command and Control", "Discovery"],
    },
    "notifyutil": {
        "desc": "Monitor and post Darwin notifications for inter-process communication.",
        "functions": ["Collection", "Command and Control", "Defense Evasion", "Discovery", "Privilege Escalation"],
    },
    "nscurl": {"desc": "Download, upload, and read files.", "functions": ["Command and Control", "Defense Evasion"]},
    "nvram": {
        "desc": "Access and manage the host's non-volatile random-access memory (NVRAM).",
        "functions": ["Discovery"],
    },
    "odutil": {"desc": "Examine or change state of opendirectoryd.", "functions": ["Discovery"]},
    "open": {"desc": "Open files, folders, apps, URLs, and header files.", "functions": ["Execution"]},
    "osacompile": {
        "desc": "Compile AppleScripts or OSA language scripts.",
        "functions": ["Command and Control", "Resource Development"],
    },
    "osascript": {
        "desc": "Execute AppleScripts and other OSA language scripts and commands.",
        "functions": ["Collection", "Credential Access", "Discovery", "Execution"],
    },
    "pbpaste": {
        "desc": "Paste the contents of clipboard to the terminal.",
        "functions": ["Collection", "Credential Access"],
    },
    "pkill": {"desc": "Kill processes by name or pattern.", "functions": ["Defense Evasion", "Impact"]},
    "plutil": {"desc": "Read, create or edit plist files.", "functions": ["Defense Evasion"]},
    "profiles": {"desc": "List and remove configuration profiles.", "functions": ["Discovery", "Impact"]},
    "safaridriver": {
        "desc": "Enable the WebDriver Safari browser API for Selenium testing.",
        "functions": ["Command and Control", "Exfiltration"],
    },
    "say": {
        "desc": "Convert text to audible speech.",
        "functions": ["Collection", "Defense Evasion", "Discovery", "Reconnaissance"],
    },
    "screencapture": {"desc": "Capture a screenshot from command line.", "functions": ["Collection"]},
    "scutil": {
        "desc": "Display basic network information, check the dns config, set the computer hostname.",
        "functions": ["Discovery"],
    },
    "security": {
        "desc": "Interact with Keychain, macOS's built-in password manager.",
        "functions": ["Credential Access", "Defense Evasion"],
    },
    "sfltool": {
        "desc": "Binary to manage the Shared File List framework.",
        "functions": ["Defense Evasion", "Discovery"],
    },
    "softwareupdate": {"desc": "Interact with the macOS software update service.", "functions": ["Discovery"]},
    "spctl": {
        "desc": "Manage the security assessment policy subsystem and Gatekeeper settings.",
        "functions": ["Defense Evasion"],
    },
    "sqlite3": {
        "desc": "Query and manage sqlite databases.",
        "functions": ["Collection", "Credential Access", "Discovery"],
    },
    "ssh-keygen": {
        "desc": "Load unsigned dynamic libraries into the ssh-keygen binary.",
        "functions": ["Defense Evasion", "Execution"],
    },
    "streamzip": {
        "desc": "File-less compression of data passed in through stdin.",
        "functions": ["Collection", "Exfiltration"],
    },
    "sw_vers": {"desc": "Prints macOS version information.", "functions": ["Discovery"]},
    "swift": {
        "desc": "Arbitrarily execute swift code from the terminal.",
        "functions": ["Defense Evasion", "Execution"],
    },
    "sysadminctl": {
        "desc": "Create/delete local accounts, guest account, enable SMB/AFP Guest access.",
        "functions": ["Exfiltration", "Impact", "Initial Access", "Persistence"],
    },
    "sysctl": {"desc": "Get macOS hardware model information.", "functions": ["Discovery"]},
    "system_profiler": {"desc": "Reports system hardware and software configuration.", "functions": ["Discovery"]},
    "systemsetup": {
        "desc": "Enable remote login, remote apple events for the machine.",
        "functions": ["Lateral Movement"],
    },
    "tccutil": {
        "desc": "Manage Transparency, Consent, and Control (TCC) permissions database.",
        "functions": ["Defense Evasion"],
    },
    "tclsh": {"desc": "Run Tcl files or shell commands from standard input.", "functions": ["Execution"]},
    "textutil": {
        "desc": "Manipulate text files in various formats.",
        "functions": ["Collection", "Credential Access", "Defense Evasion"],
    },
    "tmutil": {
        "desc": "Manage Time Machine backups.",
        "functions": ["Collection", "Defense Evasion", "Impact", "Privilege Escalation"],
    },
    "xattr": {"desc": "Display and manipulate extended attributes.", "functions": ["Defense Evasion", "Execution"]},
}
