# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent.fleet.proto import fleet_pb2 as fleet__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fleet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FleetServiceStub(object):
    """Fleet management service for centralized EDR telemetry collection.
    Agents forward findings and OCSF events to the central server via gRPC with mTLS.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/edr.fleet.FleetService/RegisterAgent',
                request_serializer=fleet__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=fleet__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.SendFindings = channel.unary_unary(
                '/edr.fleet.FleetService/SendFindings',
                request_serializer=fleet__pb2.SendFindingsRequest.SerializeToString,
                response_deserializer=fleet__pb2.SendFindingsResponse.FromString,
                _registered_method=True)
        self.SendEvents = channel.unary_unary(
                '/edr.fleet.FleetService/SendEvents',
                request_serializer=fleet__pb2.SendEventsRequest.SerializeToString,
                response_deserializer=fleet__pb2.SendEventsResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/edr.fleet.FleetService/Heartbeat',
                request_serializer=fleet__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=fleet__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class FleetServiceServicer(object):
    """Fleet management service for centralized EDR telemetry collection.
    Agents forward findings and OCSF events to the central server via gRPC with mTLS.
    """

    def RegisterAgent(self, request, context):
        """Register an agent with the fleet server. Called once on startup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFindings(self, request, context):
        """Forward security findings from the agent's LLM analyzer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEvents(self, request, context):
        """Forward normalized OCSF events for cross-host correlation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Periodic heartbeat to report agent health.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=fleet__pb2.RegisterAgentRequest.FromString,
                    response_serializer=fleet__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'SendFindings': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFindings,
                    request_deserializer=fleet__pb2.SendFindingsRequest.FromString,
                    response_serializer=fleet__pb2.SendFindingsResponse.SerializeToString,
            ),
            'SendEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEvents,
                    request_deserializer=fleet__pb2.SendEventsRequest.FromString,
                    response_serializer=fleet__pb2.SendEventsResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=fleet__pb2.HeartbeatRequest.FromString,
                    response_serializer=fleet__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edr.fleet.FleetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edr.fleet.FleetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetService(object):
    """Fleet management service for centralized EDR telemetry collection.
    Agents forward findings and OCSF events to the central server via gRPC with mTLS.
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edr.fleet.FleetService/RegisterAgent',
            fleet__pb2.RegisterAgentRequest.SerializeToString,
            fleet__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edr.fleet.FleetService/SendFindings',
            fleet__pb2.SendFindingsRequest.SerializeToString,
            fleet__pb2.SendFindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edr.fleet.FleetService/SendEvents',
            fleet__pb2.SendEventsRequest.SerializeToString,
            fleet__pb2.SendEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edr.fleet.FleetService/Heartbeat',
            fleet__pb2.HeartbeatRequest.SerializeToString,
            fleet__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
