"""Agent self-allowlist filter.

Removes entities generated by the agent's own activity (SQLite temp files,
agent-PID network/DNS, Claude dev-environment processes) **before** they
reach the graph or LLM.  This complements the user-configurable allowlist
in ``allowlist_filter.py`` and the analyzer-level preflight in
``analyzer/preflight.py``.
"""

from __future__ import annotations

from agent.processor.entity_extractor import ExtractedEntities

# Claude / Electron dev-environment process names to suppress (lowercased).
_CLAUDE_NAMES: frozenset[str] = frozenset(
    {
        "claude",
        "claude helper",
        "claude-mcp",
        "electron",
        "electron helper",
    }
)


def filter_agent_noise(entities: ExtractedEntities, agent_pid: int) -> int:
    """Remove entities caused by the agent's own operation.

    Three rules are applied:

    1. **SQLite temp files** — any ``FileNode`` whose path contains
       ``etilqs_`` (``sqlite`` reversed, used for temp files).
    2. **Agent-PID network/DNS** — edges sourced from a process with
       ``pid == agent_pid``.
    3. **Claude process names** — ``ProcessNode`` matching Claude, Claude
       Helper, claude-mcp, or Electron.  All associated edges are pruned.

    Orphaned IP/Domain/File nodes are cleaned up once at the end.

    Returns the total number of items (nodes + edges) removed.
    """
    removed = 0

    # ── Rule 1: SQLite temp files (etilqs_*) ──────────────────────────
    if entities.files:
        matched_file_ids: set[str] = set()
        kept_files = []
        for f in entities.files:
            if "etilqs_" in f.path:
                matched_file_ids.add(f.id)
                removed += 1
            else:
                kept_files.append(f)

        if matched_file_ids:
            entities.files = kept_files
            before = len(entities.file_edges)
            entities.file_edges = [e for e in entities.file_edges if e["file_id"] not in matched_file_ids]
            removed += before - len(entities.file_edges)

    # ── Rules 2 & 3: Single pass over processes ───────────────────────
    # Collect bad process IDs from both rules simultaneously.
    if not entities.processes:
        return removed

    bad_proc_ids: set[str] = set()
    claude_proc_ids: set[str] = set()
    kept_processes = []

    for proc in entities.processes:
        if proc.name.lower() in _CLAUDE_NAMES:
            claude_proc_ids.add(proc.id)
            bad_proc_ids.add(proc.id)
            removed += 1
        else:
            kept_processes.append(proc)
            if proc.pid == agent_pid:
                bad_proc_ids.add(proc.id)

    if claude_proc_ids:
        entities.processes = kept_processes

    if not bad_proc_ids:
        return removed

    # ── Filter all edge lists once with the combined bad set ──────────
    edges_changed = False

    before = len(entities.spawned_edges)
    entities.spawned_edges = [e for e in entities.spawned_edges if e["process_id"] not in bad_proc_ids]
    delta = before - len(entities.spawned_edges)
    removed += delta
    edges_changed = edges_changed or delta > 0

    before = len(entities.connected_edges)
    entities.connected_edges = [e for e in entities.connected_edges if e["process_id"] not in bad_proc_ids]
    delta = before - len(entities.connected_edges)
    removed += delta
    edges_changed = edges_changed or delta > 0

    before = len(entities.resolved_edges)
    entities.resolved_edges = [e for e in entities.resolved_edges if e["process_id"] not in bad_proc_ids]
    delta = before - len(entities.resolved_edges)
    removed += delta
    edges_changed = edges_changed or delta > 0

    before = len(entities.file_edges)
    entities.file_edges = [e for e in entities.file_edges if e["process_id"] not in bad_proc_ids]
    delta = before - len(entities.file_edges)
    removed += delta
    edges_changed = edges_changed or delta > 0

    before = len(entities.registry_edges)
    entities.registry_edges = [e for e in entities.registry_edges if e["process_id"] not in bad_proc_ids]
    delta = before - len(entities.registry_edges)
    removed += delta
    edges_changed = edges_changed or delta > 0

    # ── Single orphan cleanup ─────────────────────────────────────────
    if not edges_changed:
        return removed

    if entities.ips:
        live_ip = {e["ip_id"] for e in entities.connected_edges} | {e["ip_id"] for e in entities.resolves_to_edges}
        before = len(entities.ips)
        entities.ips = [ip for ip in entities.ips if ip.id in live_ip]
        removed += before - len(entities.ips)

    if entities.domains:
        live_dom = {e["domain_id"] for e in entities.resolved_edges} | {
            e["domain_id"] for e in entities.resolves_to_edges
        }
        before = len(entities.domains)
        entities.domains = [d for d in entities.domains if d.id in live_dom]
        removed += before - len(entities.domains)

    if entities.files:
        live_file = {e["file_id"] for e in entities.file_edges}
        before = len(entities.files)
        entities.files = [f for f in entities.files if f.id in live_file]
        removed += before - len(entities.files)

    return removed
